config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do 
      resources :users do 
        resources :lists
      end

      resources :lists, only: [:index] do 
        resources :items, only: [:create]
      end

      resources :items, only: [:update, :destroy]
  end

  devise_for :users
    resources :users 

  root to: 'welcome#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list

  validates :name, presence: true
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy 

  validates :name, presence: true
  validates :permissions, inclusion: { in: %w(private viewable open),
    message: "%{value} is not valid" }

  def public?
    permissions == 'open'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable,
  :authentication_keys => [:username]

  has_many :lists
  has_many :items, through: :lists 

  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }

  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApiController
  before_action :authenticated?

  def create
    item = Item.new(item_params)
    item.list = List.find(params[:list_id])

    authorize item 
      if item.save
        render json: item 
      else
        render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
      end
  end

  def update
    item = Item.find(params[:id])
    authorize item 
    if item.update(item_params)
      render json: item 
    else 
      render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy 
    begin 
      item = Item.find(params[:id])
      authorize item 
      item.destroy

      render json: {success: true} #, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render json: {success: false}, :status => :not_found
    end
  end 

  private

  def item_params
    params.require(:item).permit(:name, :complete)
  end

end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApiController
  before_action :authenticated?

  def index
    if params[:name].present?
      lists = current_user.lists.joins(:items).where(
        'lower(lists.name) LIKE ? or lower(items.name) LIKE ?', 
        "%#{params[:name].downcase}%",
        "%#{params[:name].downcase}%"
        )
    else
      lists = current_user.lists
    end
      render json: lists
  end

  def create
    list = List.new(list_params)

    authorize list 

    list.user = User.find(params[:user_id])
      if list.save
        render json: list
      else 
        render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
      end
  end

  def update
    list = List.find(params[:id])

    authorize list 

    if list.update(list_params)
      render json: list 
    else 
      render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      list = List.find(params[:id])
      if authorize list
        list.destroy
      else
        render json: {success: false}
      end

      render json: {success: true} #, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render json: {success: false}, :status => :not_found
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :permissions, :complete)
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  before_action :authenticated?, except: [:create]

  def index
    users = User.all 
    
    render json: users, each_serializer: UserSerializer
  end

  def create
    user = User.new(user_params)
      if user.save
        render json: user
      else
        render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
      end
  end

  def destroy
    begin 
      user = User.find(params[:id])
      user.destroy 

      render json: {}, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render json: {}, :status => :not_found 
    end
  end 

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token

  respond_to :json 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticated?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    rescue_from Pundit::NotAuthorizedError do |exception|
        # redirect_to root_url, alert: exception.message
        render json: {success: false, alert: exception.message}
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def authenticated?
    authenticate_or_request_with_http_basic do |username,password|
      resource = User.find_by_username(username)
      if resource.valid_password?(password)
        sign_in :user, resource
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all 
  end

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      flash[:notice] = "User saved successfully"
      redirect_to root_path
    else
      flash[:error] = "There was an error. Try again."
      render :new
    end

  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User updated successfully"
    else
      flash[:error] = "Invalid user information"
    end
    redirect_to edit_user_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="todoApp">
<head>
  <title>Open-Todo-API</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <li><%= link_to "Home", root_path %></li>

    <div class="pull-right user-info">
        <% if current_user %>
        Hello <%= link_to (current_user.username), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>      
        <% end %>
    </div>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h2><%= current_user.username %>'s Todo Lists</h2>

app/views/welcome/index.html.erb
<div class="container">
  <h2>My Todo Lists</h2>

  <div ng-controller="TodoListController as todoList">
    <input name="user_id" id="user_id" type="hidden" value="<%= current_user.id if current_user.present? %>">
    <span>{{todoList.remaining()}} of {{todoList.todos.length}} lists remaining</span>
    [ <a href="" ng-click="todoList.remove()">Remove</a> ]

    <div ng-repeat="todo in todoList.todos">
      <input type="checkbox" ng-model="todo.complete">
      <span class="complete-{{todo.complete}}">
        <a href="" ng-show="!showLists" ng-click="showLists=!showLists">+</a>
        <a href="" ng-show="showLists" ng-click="showLists=!showLists">-</a>
        <a href="" ng-click="showLists=!showLists">{{todo.name}}</a> {{todo.permissions}}
      </span>

      <div ng-show="showLists" class="col-lg-8 col-lg-offset-2">

        <ul class="unstyled" ng-repeat="item in todo.items">
          <input type="checkbox" ng-model="item.complete">
          <span class="complete-{{item.complete}}">{{item.name}}</span>
        </ul>   

          <ul class="unstyled">
            <form ng-submit="todoList.addItem(todo)">
              <input type="text" ng-model="todo.newItem" size="20" placeholder="Add New Item">
              <input class="btn-sm" type="submit" value="add">
            </form>
          </ul>
      </div>
    </div>

    <br>
    <form ng-submit="todoList.addTodo()">
      <input type="text" ng-model="todoList.todoText"  size="30"
             placeholder="Add new List here">
      <input class="btn-primary" type="submit" value="add">

      <label>
        <input type="radio" name="permissions"
          value="private" ng-model="todoList.permissions" />
          private
      </label>
      <label>
        <input type="radio" name="permissions"
        value="viewable" ng-model="todoList.permissions" />
        viewable
      </label>
      <label>
        <input type="radio" name="permissions"
        value="open" ng-model="todoList.permissions" />
        open
      </label>
    </form>
  </div>

  <br>
  <br>
  <%= form_tag api_lists_path, :method => 'get', :id => "api_lists_search" do %>
    <p>
      <%= text_field_tag :name, params[:name], placeholder: 'Search...' %>
      <%= submit_tag "Go", :name => nil %>
    </p>
  <% end %>

</div>